# Generated by Django 3.2.18 on 2024-10-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_event_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='ticket',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='ticketitem',
            old_name='ticket',
            new_name='order',
        ),
    ]
