# Generated by Django 3.2.18 on 2024-10-16 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20241016_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketitem',
            name='price',
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='store.order'),
        ),
    ]
