# Generated by Django 3.2.18 on 2024-10-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20241016_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
